sudo: false
language: node_js
before_install:
- chmod +x ./scripts/*
- "./scripts/before_install.sh"
script: "./scripts/build.sh"
after_success:
- "./scripts/after_success.sh"
after_failure:
- "./scripts/after_failure.sh"
env:
  global:
  - secure: owjfRWVpTjNHmdijbyvOkk0AslnQ1hX3vNUvnsn5rQUa/SG2ecPyrkk9tv+O4pjuKXSXA5/NtYhMndF8zbLZms0SD5Ke5n1wGh0XvUjwlgIB/cAGtM+2lGdstQP2SZojjdxaIz/NS8i8/UzZaHs3g0nmXIwpZ60jKnsgAXbzAheKozz2Q7kdXayOhu44BH4O8744ra5UON5AwsE34zM0tNY+HeUpZf5dLkE3Kv06IyAFu1nLwT/YJTJRSnsCMLDNQ3yv6RUOoIS8coA6OIv0ZvFQ9yVmHeXm6sAdh4J2RqsRCk2ECsxSr53vEjaMlBQXC9koXRuiJego8ot6QAZiEqzv/lWn1lF2xiJ7BNnJv8B80eTvJiUl6sUED1BKQx/br+TK4H9cx1v9P/dPwZi2UXI3MlbMlWLOJ7R4wmB29pJrzYRwH5CJNDIJgUPBgseDDyE62wljlOtTpOXUF81BCs1slaNAOLvvee7PST2p+qKr3EjXt1TGx5RUDt55VDo83zC/0DPCNhNbYrqU2e+pIH1gkYm9n6ZhSHA3Ps2PCpF1r1QEPunATrr5A6xfABLkCQDdjVhK+dYcy/vF+I0nxmtRAQm752qqnvkc/dTVO5dzS4bztzpLbzBL3e5tf+hxZRMrbnCuS/vEP+F64m1C/3C+avokQ2bJcaFQBxPA528=
  - secure: g2Dqz+LIvGe2do6Z/hAnrQBAcJLS7w6eQli6Bn+wDc4VpAOJJjuw4FCQKmMYI7CtPWLDIj+/OViQV5qfqpHOmtX8ziEY3TtkKg3W9P9RqW0uik9bKZxdsaapRTN8dFNAo9N6SGXS+0VmI23jSMOhMznOXQUQAwVjSx7HNZyox/1FdCFbVaNOVMXboPaPsCR4Ca6sZ9F2/Tfle0D3BP78x3Q6xrdzvs3AUaiw+xcnRsiOLPjPtdo7LX6ze7Kmm6RaisLQyGvdIZJohf5SVohPtz+DJSjFKDQoioSDELxl43GdWm9Vh4Lq0xFiUqiocue1sR9iUS7ewRc0zUYggPsqkVWa3okJ6v6ZFyDVlZz9Vy45hnxgD+ywBo2VoNl02HtrVFEUic0ARrHp43ior6GrTqLE6XvMYls2n17AKQaMGSeJrgS2T2/QHKbfYnejA3UTFRkDBW8JInseYi7bfM5VkM3eNzj6qeSrc05BddRQ+xQZRwu7YmIuxNMVkFvnQid7fgexIE0nVSlWfTiydqkVPrQAusT3lAt51mxgUJC3De3iooI27nQkztDz17+t059Z6dQh74AmGcihm3pJYA6XmSO6uAc8L+5bC0BrFL1AkN/PrzWOcOrWJoE+fXovmdjAUEH40iUgr88bKyBHKIeP0aQriEVC134wHj3LKCz5Fxg=
